In [2]:
import numpy as np

In [4]:
A = np.array([1,2,3,4,5,6,4,3,4], float)

In [13]:
B = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]], float)
print(A.shape)
A1=A.reshape(-1,1)
print(A.flatten())
print(B.shape)
print(B.flatten())
print(A)
print(A1)
print(A1.flatten())
np.argmax?

(9,)
[ 1.  2.  3.  4.  5.  6.  4.  3.  4.]
(3, 3)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[ 1.  2.  3.  4.  5.  6.  4.  3.  4.]
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 4.]
 [ 3.]
 [ 4.]]
[ 1.  2.  3.  4.  5.  6.  4.  3.  4.]
